//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANTA
    {
        public int idplanta { get; set; }
        public string nombrePlanta { get; set; }
        public string especie { get; set; }
        public string flor { get; set; }
        public string familia { get; set; }
        public string nombrechileno { get; set; }
        public string nombreingles { get; set; }
        public string description { get; set; }
    }
}
